name: flutter_justip
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/profile1.png
    - assets/images/profile2.png
    - assets/images/vector_chat.png
    - assets/images/vector_gas.png
    - assets/images/vector_posting.png
    - assets/images/logo.png
